!o::
Send, {AltDown}{F4}
Sleep, 250
Send, {AltUp}
Return

!u::
loop 50
{
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25
    Run, https://account.microsoft.com/?ref=MeControl&refd=www.microsoft.com
    Sleep, 25000
    Send, {AltDown}{F4}
    Sleep, 250
    Send, {AltUp}
    Sleep, 500
}
Return

!y::
Loop, 100
{
    Sleep, 2500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
    Send, ^r
    Sleep, 500
    Send, ^{Tab}
    Sleep, 500
}