!y::
Send, Star Wars 1
Sleep, 250
Send, {Enter}
Sleep, 250
Send, {CtrlDown}T{CtrlUp}
Sleep, 250
/*
Send, Star Wars 2
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 3
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 4
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 5
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 6
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 7
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 8
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Send, Star Wars 9
Sleep, 250
Send, {Enter}
Sleep, 250
Send, ^T
Sleep, 250
Return